### ISSUE TITLE
Scientific notation in tweet IDs

### ISSUE THREAD

**Issue by gattilorenz** [Gautamshahi/Misinormation_COVID-19#1]
I have noticed that at least in dataset 1 there is a problem with the tweet IDs, where they are sometimes written in scientific notation, e.g.
1.2316E+18	FALSE

**Comment by Gautamshahi** [comment]
Hi, It might be an issue of your editor. Which editor or tool are you using?

**Comment by gattilorenz** [comment]
grep, after downloading it from Github:

`$ grep -n E+ *`
`Dataset-I:339:1.25018E+18	FALSE`
`Dataset-I:490:1.24021E+18	FALSE`
`Dataset-I:859:1.2316E+18	FALSE`

Thus lines 339, 490, 859 of Dataset-I

**Comment by Gautamshahi** [comment]
Thanks for pointing out, I have updated the dataset with more classes.

**Comment by gattilorenz** [comment]
Nice, thanks!
